name: marp-to-pages
concurrency: marp-to-pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install and Build 🔧
        run: |
            npx @marp-team/marp-cli@4.1.2 presentation.md -o index.html
            cp themes/academic.css presentation/themes/
            mv presentation public

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: public # The folder the action should deploy.
