name: marp-to-pages
concurrency: marp-to-pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Ensure build dir exists
        run: mkdir -p build

      - name: Copy images directory (if exists)
        run: if [[ -d img ]]; then cp -R img build/img; fi

      - name: Copy themes directory (if exists)
        run: if [[ -d themes ]]; then cp -R themes build/themes; fi

      - name: Marp Build (presentation.md)
        uses: docker://marpteam/marp-cli:v4.1.2
        with:
          args: presentation.md -o build/index.html
        env:
          MARP_USER: root:root

      - name: Deploy to Github Pages
        if: ${{ github.event_name == 'push' }}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: ./build/
