name: marp-to-pages
concurrency: marp-to-pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install and Build 🔧
        run: |
            npm install -g @marp-team/marp-cli @4.1.2
            marp --theme themes/academic.css presentation.md -o index.html
            mv index.html public

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: public # The folder the action should deploy.
